default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: slackly_dev

test:
  <<: *default
  database: slackly_test

production:
  <<: *default
  database: slackly_prod
